### ISSUE TITLE
Custom chooser block?

### ISSUE THREAD

**Issue by mobweb** [extendix/Extendix_AdminFormChooserButton#4]
Hello,

Very useful extension!

But I'm having some troubles implementing my custom chooser block. I'd like to use the product chooser block but modify some columns in the grid.

Here's what I've done:

In my Blockname.php:

```
Mage::helper('extendix_admin_form_chooser_button/chooser')->createChooser($model, $fieldset, array(
    'input_label' => Mage::helper('adminhtml')->__('Product'),
    'button_text' => $this->__('Select Product...'),
    'input_name' => 'product_selector',
), 'company_extension/catalog_product_widget_chooser');
```

And for the chooser block I've extended the default block:

`class Company_Extension_Block_Catalog_Product_Widget_Chooser extends Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser`

When I debug `Company_Extension_Block_Catalog_Product_Widget_Chooser::__construct()` it gets called as expected, but my `Company_Extension_Block_Catalog_Product_Widget_Chooser::__prepareColumns()` is never called, no matter what I do. Instead, it's still calling the original `Mage_Adminhtml_Block_Catalog_Product_Widget_Chooser::__prepareColumns()`.

Do you have any idea what the issue could be?

**Comment by mobweb** [comment]
Never mind, I figured it out! :)

**Comment by ceckoslab** [comment]
@mobweb Thanks!
